<a href="https://www.kaggle.com/code/nishkoder/word2vec-model?scriptVersionId=162773150" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

## Project Index
1. ### [Import Libirary](#1)
2. ### [Download all nltk required packages](#2)
3. ### [Read all the files](#3)
    * ### [Experiment with one file](#4)
    * ### [Simple preprocess](#5)
    * ### [On complete files](#6)
4. ### [Configure Model](#7)
5. ### [Train Model](#8)
6. ### [Validate Model with some examples](#9)


        

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/game-of-thrones-books/004ssb.txt
/kaggle/input/game-of-thrones-books/005ssb.txt
/kaggle/input/game-of-thrones-books/001ssb.txt
/kaggle/input/game-of-thrones-books/002ssb.txt
/kaggle/input/game-of-thrones-books/003ssb.txt


## Import Libirary <a id="1" />

In [2]:
import pandas as pd
import numpy as np
import os
import gensim
import nltk
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

## Download all nltk required packages <a id="2" />

In [3]:
nltk.download("all")

[nltk_data] Downloading collection 'all'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to /usr/share/nltk_data...
[nltk_data]    |   Package abc is already up-to-date!
[nltk_data]    | Downloading package alpino to /usr/share/nltk_data...
[nltk_data]    |   Package alpino is already up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     /usr/share/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger is already up-
[nltk_data]    |       to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     /usr/share/nltk_data...
[nltk_data]    |   Unzipping
[nltk_data]    |       taggers/averaged_perceptron_tagger_ru.zip.
[nltk_data]    | Downloading package basque_grammars to
[nltk_data]    |     /usr/share/nltk_data...
[nltk_data]    |   Package basque_grammars is already up-to-date!
[nltk_data]    | Downloading package bcp47 to /usr/share/nltk_data...
[nltk_data]    | Downloading pa

True

## Read all the files<a id="3"/>

In [4]:
story = []

In [5]:
for _,_,filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        story.append(filename)

### Experiment with one file<a id="4"/>

In [6]:
f = open(f"/kaggle/input/game-of-thrones-books/{story[0]}", encoding="unicode_escape")

In [7]:
corpus=f.read()

In [8]:
raw_sentences = sent_tokenize(corpus)

### simple preprocess <a id="5"/>

In [9]:
for i in raw_sentences:
    print(simple_preprocess(i))

['version', 'history', 'reedited', 'by', 'maelstrom', 'feast', 'for', 'crows', 'book', 'four', 'song', 'of', 'ice', 'and', 'fire', 'george']
['martin', 'prologue', 'dragons', 'said', 'mollander']
['he', 'snatched', 'withered', 'apple', 'off', 'the', 'ground', 'and', 'tossed', 'it', 'hand', 'to', 'hand']
['throw', 'the', 'apple', 'urged', 'alleras', 'the', 'sphinx']
['he', 'slipped', 'an', 'arrow', 'from', 'his', 'quiver', 'and', 'nocked', 'it', 'to', 'his', 'bowstring']
['should', 'like', 'to', 'see', 'dragon', 'roone', 'was', 'the', 'youngest', 'of', 'them', 'chunky', 'boy', 'still', 'two', 'years', 'shy', 'of', 'manhood']
['should', 'like', 'that', 'very', 'much', 'and', 'should', 'like', 'to', 'sleep', 'with', 'rosey', 'arms', 'around', 'me', 'pate', 'thought']
['he', 'shifted', 'restlessly', 'on', 'the', 'bench']
['by', 'the', 'morrow', 'the', 'girl', 'could', 'well', 'be', 'his']
['will', 'take', 'her', 'far', 'from', 'oldtown', 'across', 'the', 'narrow', 'sea', 'to', 'one', 'of',

### implement on all files <a id="6" />

In [10]:
story = []
for dirname,_,filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        filepath = os.path.join(dirname, filename)
        with open(filepath, encoding="unicode_escape") as f:
            corpus = f.read()
        raw_sentences = sent_tokenize(corpus)
        for sent in raw_sentences:
            story.append(simple_preprocess(sent))

In [11]:
len(story)

145018

In [12]:
story[0]

['version',
 'history',
 'reedited',
 'by',
 'maelstrom',
 'feast',
 'for',
 'crows',
 'book',
 'four',
 'song',
 'of',
 'ice',
 'and',
 'fire',
 'george']

## Configure Model<a id="7"/>

In [13]:
model = gensim.models.Word2Vec(window=10, min_count=5, vector_size=150)

In [14]:
model.build_vocab(story)

In [15]:
model.corpus_count

145018

In [16]:
model.epochs

5

In [17]:
model.corpus_total_words

1725638

## Train Model <a id="8"/>

In [18]:
model.train(
    story, 
    total_examples=model.corpus_count, 
    epochs=model.epochs
)

(6483536, 8628190)

## Validate Model with some examples<a id="9"/>

In [19]:
model.wv["king"]

array([ 1.6880441 ,  1.5902987 , -0.7445194 , -1.0718412 , -2.5979495 ,
       -1.1184201 , -1.0068777 ,  1.2815403 , -1.2888188 ,  0.28666776,
        0.74707276, -0.02130994, -0.7132115 , -1.0071955 , -1.6059723 ,
       -0.5105341 ,  0.68387836,  2.5302734 , -1.4178232 ,  2.5162036 ,
       -1.9528123 ,  1.330539  , -0.42507547, -0.62819904,  0.8981018 ,
       -0.49606457, -1.1929507 , -2.4877555 , -0.20465368,  2.5743945 ,
        3.1984766 , -0.5782154 , -0.77819467, -1.568729  ,  1.2213918 ,
       -0.44010612,  0.7705365 ,  1.4608966 ,  1.7686255 ,  0.4323181 ,
        0.6878886 ,  1.728972  , -2.3603947 ,  0.16137296,  0.12994716,
        0.7087639 , -0.14577179,  0.8497557 ,  1.5627269 , -1.3277876 ,
       -2.5181344 , -0.62734175,  1.8824586 , -1.0045706 , -0.19176273,
       -1.5174088 ,  1.5622045 ,  0.32072186,  2.6933184 , -0.09493455,
        1.6166135 , -1.1135244 , -0.9204082 ,  2.2394853 , -0.8278002 ,
       -0.5669392 , -0.5066425 ,  0.9461245 ,  0.58531564, -0.01

In [20]:
len(model.wv["king"])

150

In [21]:
model.wv["man"]

array([-4.64054555e-01,  9.27575409e-01, -2.25700453e-01, -8.12222600e-01,
       -1.32134914e+00,  2.27238154e+00,  8.60241532e-01,  1.30172479e+00,
        1.19614267e+00, -6.34811997e-01, -6.59316659e-01,  2.08580780e+00,
       -9.62785840e-01, -1.69458163e+00, -1.20774102e+00, -1.45642102e+00,
       -9.36170816e-02,  2.59808600e-01, -1.79179478e+00, -1.29229218e-01,
        5.02701938e-01,  1.67214358e+00,  1.56714785e+00, -1.09654081e+00,
        2.11400747e-01, -1.39285541e+00,  5.43926477e-01, -1.04671919e+00,
       -1.10701680e+00,  1.18831813e-01,  1.84423411e+00,  2.06396484e+00,
        1.13900650e+00, -3.44092667e-01,  1.30587840e+00, -6.54007196e-01,
       -8.20122480e-01, -1.40295342e-01,  1.15565825e+00, -1.71688044e+00,
        1.07840610e+00, -5.27295582e-02, -1.26830661e+00,  1.90990961e+00,
        4.87655133e-01,  5.43846130e-01, -6.63266703e-02, -1.58377731e+00,
        8.02924573e-01, -2.19362640e+00,  1.35292482e+00, -1.94959924e-01,
        1.32873058e+00,  

In [22]:
model.wv["women"]

array([ 0.29054815,  0.33764818, -0.9218361 , -1.2553424 ,  0.20281395,
       -0.8479955 , -0.23366083, -0.35523218,  1.0796294 , -0.2584959 ,
       -0.23414774,  0.06463024,  0.12853949, -1.6857455 , -1.1080935 ,
        0.3780153 ,  0.07149089, -0.5290191 , -0.5544897 , -0.5085461 ,
       -0.19460896, -1.0108807 , -0.47499466,  0.70559746,  0.03345383,
        0.05990815, -0.30425566, -0.83309114, -0.07161295,  0.8035403 ,
        0.09263976,  1.3059329 ,  0.6594434 , -1.4292153 ,  0.3945043 ,
       -0.17345214, -0.04389433, -0.5344741 , -0.03113277,  0.17022823,
        0.27937916,  0.38119194,  0.2081975 ,  0.48947018,  0.7571268 ,
       -0.56071347, -0.04147476,  0.37673646, -0.6869205 , -0.8102837 ,
        0.40123236, -0.7189282 , -0.29587287, -0.09796649, -0.82791597,
       -0.19496582,  0.08177866,  1.2217029 , -0.35998413,  0.94492066,
       -0.83697623, -0.08305359, -0.14458452,  1.0103549 , -0.9095565 ,
        0.41036707,  0.18078886, -0.9350895 ,  0.36338028,  0.29

In [23]:
model.wv.most_similar("king")

[('realm', 0.6516013145446777),
 ('prince', 0.6457929611206055),
 ('baratheon', 0.6419500112533569),
 ('usurper', 0.6353543400764465),
 ('victory', 0.6099954843521118),
 ('throne', 0.6096773743629456),
 ('targaryen', 0.5975794196128845),
 ('battle', 0.5850698947906494),
 ('conqueror', 0.5841764807701111),
 ('tourney', 0.583130419254303)]

In [24]:
model.wv.most_similar("daenerys")

[('stormborn', 0.7938127517700195),
 ('targaryen', 0.7570684552192688),
 ('myrcella', 0.6936962604522705),
 ('princess', 0.6916447877883911),
 ('queen', 0.6805450320243835),
 ('unburnt', 0.6758803725242615),
 ('margaery', 0.6622711420059204),
 ('elia', 0.6526492834091187),
 ('viserys', 0.6381768584251404),
 ('dorne', 0.6373329758644104)]

In [25]:
model.wv.most_similar("queen")

[('princess', 0.7653310298919678),
 ('margaery', 0.7340853810310364),
 ('daenerys', 0.6805449724197388),
 ('prince', 0.6721348166465759),
 ('myrcella', 0.6500126123428345),
 ('stormborn', 0.6401669979095459),
 ('cersei', 0.6391321420669556),
 ('mother', 0.6372287273406982),
 ('elia', 0.6174097657203674),
 ('targaryen', 0.6146809458732605)]

In [26]:
model.wv.doesnt_match(["jon","rikon","arya","sensa","bran"])

'jon'

In [27]:
model.wv.get_normed_vectors()

array([[-0.06523525,  0.02032548, -0.07544192, ...,  0.0354284 ,
         0.00430478, -0.10542724],
       [ 0.02527411,  0.01273258,  0.026749  , ..., -0.02234457,
         0.12160623, -0.11073784],
       [-0.0030173 ,  0.14842615, -0.01470316, ..., -0.11102146,
         0.00451377, -0.13877872],
       ...,
       [ 0.06395016, -0.03995974,  0.01198203, ..., -0.14972107,
         0.09955662, -0.14350829],
       [ 0.06249563, -0.08408911, -0.0578259 , ..., -0.149465  ,
         0.16852719, -0.13235834],
       [-0.08325773, -0.06497371, -0.00098556, ..., -0.06163394,
         0.09838367, -0.11965078]], dtype=float32)

In [28]:
model.wv.index_to_key

['the',
 'and',
 'to',
 'of',
 'he',
 'his',
 'was',
 'you',
 'her',
 'in',
 'it',
 'had',
 'that',
 'she',
 'as',
 'with',
 'him',
 'not',
 'but',
 'for',
 'they',
 'is',
 'at',
 'on',
 'said',
 'my',
 'have',
 'be',
 'lord',
 'them',
 'no',
 'from',
 'would',
 'were',
 'me',
 'your',
 'one',
 'all',
 'when',
 'will',
 'ser',
 'if',
 'so',
 'their',
 'we',
 'could',
 'are',
 'man',
 'there',
 'this',
 'up',
 'been',
 'what',
 'did',
 'by',
 'king',
 'do',
 'men',
 'back',
 'out',
 'more',
 'or',
 'who',
 'down',
 'well',
 'than',
 'only',
 'like',
 'jon',
 'some',
 'father',
 'old',
 'hand',
 'even',
 'too',
 'tyrion',
 'before',
 'never',
 'an',
 'off',
 'see',
 'know',
 'into',
 'made',
 'now',
 'eyes',
 'black',
 'told',
 'lady',
 'thought',
 'time',
 'then',
 'how',
 'long',
 'has',
 'can',
 'might',
 'us',
 'come',
 'where',
 'here',
 'through',
 'face',
 'still',
 'head',
 'red',
 'll',
 'way',
 'boy',
 'page',
 'must',
 'once',
 'queen',
 'good',
 'two',
 'brother',
 'night',
 

In [29]:
model.save("word2vec.model")